# Generated by Django 5.2.8 on 2025-12-05 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('raise_error', models.BooleanField(default=False, help_text='If True, the process will raise an error')),
                ('error_code', models.IntegerField(default=0, help_text='Catched error code')),
                ('status', models.CharField(choices=[('B0', 'B0'), ('B1', 'B1'), ('B2', 'B2'), ('Err', 'Err')], default='B0', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('raise_error', models.BooleanField(default=False, help_text='If True, the process will raise an error')),
                ('error_code', models.IntegerField(default=0, help_text='Catched error code')),
                ('status', models.CharField(choices=[('C0', 'C0'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3')], default='C0', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('raise_error', models.BooleanField(default=False, help_text='If True, the process will raise an error')),
                ('error_code', models.IntegerField(default=0, help_text='Catched error code')),
                ('status', models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5')], default='A0', max_length=3)),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abstract.b')),
            ],
        ),
        migrations.AddField(
            model_name='b',
            name='c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abstract.c'),
        ),
    ]
