# Generated by Django 5.2.8 on 2025-12-12 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a',
            name='b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abstract.b'),
        ),
        migrations.AlterField(
            model_name='b',
            name='c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abstract.c'),
        ),
    ]
