# Generated by Django 5.2.8 on 2025-12-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0002_alter_a_b_alter_b_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a',
            name='status',
            field=models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('Err', 'Err')], default='A0', max_length=3),
        ),
    ]
