# Generated by Django 5.2.8 on 2025-12-05 05:56

import os
from django.db import migrations
from clickhouse.client import client

def create_clickhouse_table(apps, schema_editor):
    """Create ClickHouse table for logging"""
    
    # Create table for logging with common fields
    # Note: Fields that may be missing are nullable or have defaults
    create_table_sql = """
    CREATE TABLE IF NOT EXISTS logs (
        message Nullable(String),
        levelname LowCardinality(Nullable(String)),
        filename Nullable(String),
        module Nullable(String),
        lineno Nullable(UInt32),
        exc_info Nullable(String),
        created Nullable(DateTime64(3)),
        msecs Nullable(Float64),
        relativeCreated Nullable(Float64),
        asctime Nullable(String),
        name Nullable(String),
        pathname Nullable(String),
        funcName Nullable(String),
        thread Nullable(UInt64),
        threadName Nullable(String),
        processName Nullable(String),
        process Nullable(UInt64),
        stack_info Nullable(String),
        exc_text Nullable(String),
        msg Nullable(String),
        levelno Nullable(UInt8),
        args Nullable(String),
        _timestamp DateTime DEFAULT now()
    ) ENGINE = MergeTree()
    ORDER BY (_timestamp, levelname)
    PARTITION BY toYYYYMM(_timestamp)
    TTL _timestamp + INTERVAL 90 DAY
    SETTINGS index_granularity = 8192, allow_nullable_key = 1
    """
    
    client.command(create_table_sql)


def drop_clickhouse_table(apps, schema_editor):
    """Drop ClickHouse table"""
    client.command("DROP TABLE IF EXISTS logs")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_clickhouse_table, drop_clickhouse_table),
    ]
