# Generated by Django 5.2.8 on 2025-12-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=16)),
                ('customer_received', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
