# Generated by Django 4.1.13 on 2025-05-28 10:07

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_completed', models.BooleanField(default=False)),
                ('errors_count', models.PositiveIntegerField(default=0)),
                ('last_error_dt', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True)),
                ('app_label', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('instance_id', models.PositiveIntegerField()),
                ('process_name', models.CharField(max_length=100)),
                ('transition_name', models.CharField(max_length=100)),
                ('args', models.JSONField(blank=True, default=list)),
                ('kwargs', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddIndex(
            model_name='transitionmessage',
            index=models.Index(fields=['created', 'is_completed'], name='django_logi_created_59f359_idx'),
        ),
        migrations.AddConstraint(
            model_name='transitionmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_completed', False)), fields=('app_label', 'model_name', 'instance_id'), name='only_one_uncompleted_transition_per_instance'),
        ),
    ]
