# Generated by Django 5.2.8 on 2026-02-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_logic_ext', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitionmessage',
            name='process_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
