# Generated by Django 5.2.8 on 2026-02-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_logic_ext', '0002_transitionmessage_process_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitionmessage',
            name='field_name',
            field=models.CharField(default='status', max_length=100),
        ),
    ]
